##############

#
# Tunnels between Hubs in the same region
#

{% if region_id == 1 %}
    {# the dict key is the 'dc_id' context of the Hub #}
    {% set hubs = {
        1: [
                {   'name': 'H1H2', 'interface': lan.port, 'nexthop':  lan.network|ipmath(254),
                    'remote_gw': datacenter.west.second.lan.ip,
                    'localid': 'WEST_DC1', 'comment': 'Tunnel between WEST-DC1 and WEST-DC2'
                },
                ],
        2: [
                {   'name': 'H1H2', 'interface': lan.port, 'nexthop':  lan.network|ipmath(254),
                    'remote_gw': datacenter.west.first.lan.ip,
                    'localid': 'WEST_DC2', 'comment': 'Tunnel between WEST-DC1 and WEST-DC2'
                },
                ]
        }
    %}
{% else %} {# East region #}
    {% set hubs = {}
    %}
{% endif %}

{% set phase1s = hubs.get(dc_id, []) %} {# get phase1s of a Hub. If the dict key does not exist return empty list #}

{% for phase1 in phase1s %}
    config router static
        edit {{30+loop.index0}}
            set dst {{phase1.remote_gw}}/32
            set device {{phase1.interface}}
            set gateway {{phase1.nexthop}}
            set comment "{{phase1.comment}}"
        next
    end

    config vpn ipsec phase1-interface
        edit "{{phase1.name}}"
            set type static
            set interface "{{phase1.interface}}"
            set ike-version 2
            set peertype any
            set localid "{{phase1.localid}}"
            set exchange-fgt-device-id enable

            set net-device enable
            set add-route disable

            set auto-discovery-sender enable
            set auto-discovery-receiver enable
            set auto-discovery-forwarder enable

            set exchange-ip-addr4 {{loopback}}
            {% if ipv6 %}
                set exchange-ip-addr6 {{loopback|ipv4_to_ipv6}}
            {% endif %}

            set dpd on-idle
            set dpd-retrycount 3
            set dpd-retryinterval 5
            set psksecret fortinet
            set remote-gw {{phase1.remote_gw}}
            set comments "{{phase1.comment}}"
            set transport udp {# Force IKE/IPsec over UDP, no fallback to TCP #}
            {{ "set encapsulation vpn-id-ipip" if vrf_segmentation }}
            {% if npu == 'NP6' %}
                set proposal aes128-sha256 aes128-sha1
            {% else %}
                set proposal aes128gcm-prfsha256 aes128-sha256 aes128-sha1
            {% endif %}
            set dhgrp 19
        next
    end

    config vpn ipsec phase2-interface
        edit "{{phase1.name}}"
            set phase1name "{{phase1.name}}"
            set keepalive enable
            {% if npu == 'NP6' %}
                set proposal aes128-sha256 aes128-sha1
            {% else %}
                set proposal aes128gcm aes128-sha256 aes128-sha1
            {% endif %}
            set dhgrp 19
        next
        {% if ipv6 %}
            edit "{{phase1.name}}_v6"
                set phase1name "{{phase1.name}}"
                set auto-negotiate enable
                {% if npu == 'NP6' %}
                    set proposal aes128-sha256 aes128-sha1
                {% else %}
                    set proposal aes128gcm aes128-sha256 aes128-sha1
                {% endif %}
                set dhgrp 19
                set src-addr-type subnet6
                set dst-addr-type subnet6
            next
        {% endif %}
    end

    config system interface
        edit "{{phase1.name}}"
            set monitor-bandwidth enable
            set vrf {{vrf_pe}}
        next
    end
{% endfor %}
