### SD-WAN Duplication rules ----------------------------------------------------------------

{# SD-WAN duplication must be defined after LAN zone #}

config system sdwan
    config duplication
        # from Branches
        edit 1
            set srcintf "BRANCHES"
            set srcaddr "Corporate"
            set dstintf "LAN"
            set dstaddr "Corporate"
            set service "UDP/5002"
            # 'on-demand' duplication is only available for HUB->BRANCH direction in FOS 8.0
            # 'force' duplication is used in HUB->BRANCH direction with FOS 7.6
            set packet-duplication {{ "on-demand" if FOS >= 8_000_000 else "force" }}
            set packet-de-duplication enable
        next
    end
end