###############################################################################################################
# IPsec

{% set overlay1 = '10.201.' ~ dc_id %}
{% set overlay2 = '10.202.' ~ dc_id %}
{% set overlay3 = '10.203.' ~ dc_id %}

{% if overlay == 'no_ip' %}
    {% set phase1s = [
        { 'name': 'EDGE_INET1', 'interface': wan.inet1.name, 'network_id': dc_id ~ '1', 'localid': name~"_INET1" },
        { 'name': 'EDGE_INET2', 'interface': wan.inet2.name, 'network_id': dc_id ~ '2', 'localid': name~"_INET2" },
        ]
    %}
{% endif %}

config vpn ipsec fec
    edit "fec_profile"
        config mappings
            edit 1
                set base 10
                set redundant 1
            next
        end
    next
end

{% for phase1 in phase1s %}
    config vpn ipsec phase1-interface
        edit "{{phase1.name}}"
            set fec-ingress enable
            set fec-egress enable
            set fec-health-check SLA_EDGE
            set fec-mapping-profile fec_profile
        next
    end
{% endfor %}

