###############################################################################################################
# IPsec

{% set overlay1 = '10.201' %}
{% set overlay2 = '10.202' %}
{% set overlay3 = '10.203' %}

{%- set dc1 = datacenter.first -%}
{%- set dc2 = datacenter.second -%}

{%- set phase1s = [
    {   'name': 'H1_INET1', 'interface': wan.inet1.name, 'remote_gw': dc1.inet1.ip, 'link_cost': 0,
        'networkid': dc1.id~'1', 'localid': name~'_INET1', 'status': 'up',
        'ip': overlay1~'.'~dc1.id~'.'~branch_id, 'remote_ip':overlay1~'.'~dc1.id~'.254', 'cross_underlay': false,
    },
    {   'name': 'H1_INET2', 'interface': wan.inet2.name, 'remote_gw': dc1.inet2.ip, 'link_cost': 5,
        'networkid': dc1.id~'2', 'localid': name~'_INET2', 'status': 'up',
        'ip': overlay2~'.'~dc1.id~'.'~branch_id, 'remote_ip':overlay2~'.'~dc1.id~'.254', 'cross_underlay': false,
    },
    ]
-%}

config vpn ipsec fec
    edit "fec_profile"
        config mappings
            edit 1
                set base 10
                set redundant 1
            next
        end
    next
end

{%- for phase1 in phase1s %}
    {% if phase1.cross_underlay and not full_mesh_ipsec %}
        {% continue %}
    {% endif %}
    config vpn ipsec phase1-interface
        edit "{{phase1.name}}"
            set fec-ingress enable
            set fec-egress enable
            set fec-health-check SLA_VPN
            set fec-mapping-profile fec_profile
        next
    end
{% endfor %}
