# dynamic BGP peerings with Branches in local region (iBGP peering)
# since the Branch is not a route-reflector, it will not re-advertise the iBGP prefixes learned from the Hub
# it will only advertise its own 'network' prefixes or prefixes learned from 'redistribute'

{% set local_ASN = 65000 + region_id %}

config router bgp
    config neighbor-group
        edit "ADVPN"
            set description "Dynamic BGP over intra-regional ADVPN shortcuts"
            set passive disable
            set remote-as {{local_ASN}}
            set interface "lo-BGP"
            set update-source "lo-BGP"
            set advertisement-interval 1
            set soft-reconfiguration enable
            set capability-graceful-restart enable
            set next-hop-self enable
        next
    end
    config neighbor-range
        edit 1
            set prefix 10.200.{{region_id}}.0 255.255.255.0
            set neighbor-group "ADVPN"
        next
    end
end
