###############################################################################################################
# FW addresses and groups

config firewall address
    edit "lo-SDWAN-HC"
        set subnet 10.200.{{region_id}}.254 255.255.255.255
    next
    edit "lo-BGP"
        set subnet {{loopback}} 255.255.255.255
    next
    edit "lo-BGP-global-summary"
        set subnet 10.200.0.0 255.255.0.0
        set allow-routing enable
    next
    edit "lo-BGP-regional-summary"
        set subnet 10.200.{{region_id}}.0 255.255.255.0
        set allow-routing enable
    next
#     edit "WEST-EXT"
#         set subnet 10.12.0.0 255.255.255.0
#         set allow-routing enable
#     next
#     edit "LAN"
#         set subnet {{lan.network}}
#         set allow-routing enable
#     next
end

# config firewall addrgrp
#     edit "DataCenters"
#         set member "WEST-EXT"
#     next
# end

config firewall address6
    edit "Corporate"
        set ip6 2000:10::/32
    next
    edit "lo-SDWAN-HC"
        set ip6 2000:10:200:{{region_id}}::254/128
    next
    edit "lo-BGP"
        set ip6 {{loopback|ipv4_to_ipv6}}/128
    next
    edit "lo-BGP-global-summary"
        set ip6 2000:10:200::/48
    next
    edit "lo-BGP-regional-summary"
        set ip6 2000:10:200:{{region_id}}::/64
    next
#     edit "WEST-EXT"
#         set subnet 10.12.0.0 255.255.255.0
#         set allow-routing enable
#     next
#     edit "LAN"
#         set subnet {{lan.network}}
#         set allow-routing enable
#     next
end


