###############################################################################################################
# IPsec FEC (must be configured after IPsec and after SD-WAN)

config vpn ipsec fec
    edit "fec_profile"
        config mappings
            edit 1
                set base 6
                set redundant 3
                set packet-loss-threshold 2
            next
            edit 2
                set base 10
                set redundant 3
                set packet-loss-threshold 1
            next
            edit 3
                set base 20
                set redundant 1
            next
        end
    next
end


{%- set phase1s = [ 'EDGE_INET1', 'EDGE_INET2', 'EDGE_INET3' ] %}

config vpn ipsec phase1-interface
    {% for phase1 in phase1s %}
        edit "{{phase1}}"
            set fec-egress enable
            set fec-ingress enable
            set fec-health-check "SLA_EDGE"
            set fec-mapping-profile "fec_profile"
            set fec-base 20
            set fec-redundant 1
            set fec-codec rs
        next
    {% endfor %}
end
