#########################################################################################
# Static routes

{% if vrf_wan == 0 %}
# OOB is in VRF 0 so no need for default static routes 999 via Fabric Studio gateway if the WAN VRF is also in VRF 0
# since there will already exist default routes via the Internet WAN interfaces
    config router static
        delete 999
    end
{% endif %}

# MPLS underlay (distance 21 to make it float after possible eBGP similar route)

config router static
    edit 1
        unset gateway
        unset device
#        set dst {{wan.mpls_summary.network}}
        set dstaddr "MPLS_summary"
        set device "{{wan.mpls1.name}}"
        {{ "set dynamic-gateway enable" if wan.mpls1.dhcp else "set gateway %s.254"%(wan.mpls1.subnet) }}
        set comment "MPLS underlay"
        set distance 21
    next
end

# Static default-routes

config router static
    edit 2
        set sdwan-zone "INTERNET"
        set comment "VRF {{vrf_wan}} default-route via Internet"
    next
end

# Regional loopback summary blackhole for BGP summarization

config router static
    edit 200
        set dstaddr "lo-BGP-regional-summary"
        set comment "Regional BGP loopback summary"
        set blackhole enable
        set vrf {{vrf_pe}}
    next
end

# Corporate summaries
# Advertise global RFC1918 LAN summaries
# A 'tag' is applied so that it can be used during redistribution of static routes into BGP

config router static
    edit 10
        set dstaddr "Corporate"
        set blackhole enable
        set comment "Corporate summary"
        set tag 1918
        set vrf {{vrf_pe}}
        set distance 1
    next
end
