###############################################################################################################
# Static default-routes

# With BGP-on-loopback design, it is recommended to configure **default route** on the Spokes towards all the overlays
# default-route is always configured over all overlays
config router static
    edit 2
        set sdwan-zone "INTERNET" {{"SIA" if sia}} "VPN"
        set comment "Default-route via Internet and all overlays"
    next
#     edit 3
#         set dstaddr "BGP-HUBS"
#         set distance 254
#         set blackhole enable
#         {{ "set vrf "~vrf_pe if vrf_segmentation }}
#         set comment "Prevent trying to establish BGP Peering with HUB1 via HUB2 (or HUB2 via HUB1)"
#     next
end

