###############################################################################################################

{% set clients = [
    { 'name': 'BR1_DATA', 'ip': '10.1.10.7' },
    { 'name': 'BR1_VOICE', 'ip': '10.1.11.7' },
    { 'name': 'BR1_VIDEO', 'ip': '10.1.12.7' },
    { 'name': 'BR1_XTD', 'ip': '10.12.0.111' },

    { 'name': 'BR2_DATA', 'ip': '10.2.10.7' },
    { 'name': 'BR2_VOICE', 'ip': '10.2.11.7' },
    { 'name': 'BR2_VIDEO', 'ip': '10.2.12.7' },
    { 'name': 'BR2_XTD', 'ip': '10.12.0.222' },

    { 'name': 'BR3_DATA', 'ip': '10.3.10.7' },
    { 'name': 'BR3_VOICE', 'ip': '10.3.11.7' },
    { 'name': 'BR3_VIDEO', 'ip': '10.3.12.7' },
    { 'name': 'BR3_XTD', 'ip': '10.34.0.33' },

    { 'name': 'BR4_DATA', 'ip': '10.4.10.7' },
    { 'name': 'BR4_VOICE', 'ip': '10.4.11.7' },
    { 'name': 'BR4_VIDEO', 'ip': '10.4.12.7' },
    { 'name': 'BR4_XTD', 'ip': '10.34.0.44' },
]%}

{# Sniffer aliases #}

config system alias
    edit "sniff_advpnv2"
        set command "diag sniffer packet any \'udp port 4684\' 4"
    next
    {% for dport in (8080,8081,8082,8083) %}
    edit "sniff_udp{{dport}}"
        set command "diag sniffer packet any \'udp port {{dport}}\' 4"
    next
    {% endfor %}
    {% for client in clients %}
        edit "sniff_{{client.name}}"
            set command "diagnose sniffer packet any \'host {{client.ip}}\' 4"
        next
    {% endfor %}
end


{# Debug flow aliases #}

config system alias
    {% for dport in (8080,8081,8082,8083) %}
    edit "flow_udp{{dport}}"
        set command "
diag debug flow filter clear
diag debug flow show function-name enable
diag debug flow filter proto 17
diag debug flow filter port {{dport}}
diag debug flow trace start 10
diag debug console time disable
diag debug enable"
    next
    {% endfor %}
{% for client in clients %}
    edit "flow_{{client.name}}"
        set command "
diag debug flow filter clear
diag debug flow show function-name enable
diag debug flow filter addr {{client.ip}}
diag debug flow trace start 10
diag debug console time disable
diag debug enable"
    next
{% endfor %}

    edit "flow_stop"
        set command "
diag debug flow trace stop
diag debug flow filter clear
diag debug console time disable
diag debug disable"
    next
end
