###############################################################################################################
# Internet and OOB management interfaces

{% set wan_underlays = [ wan.inet1, wan.inet2,  wan.mpls1 ] %}

config system interface

    {% if mgmt.vlanid == 0 %}
        edit "{{mgmt.interface}}"
    {% else %}
        edit "OOB_MGMT"
    {% endif %}
            set vrf {{mgmt.vrfid}}
        next

    {% for underlay in wan_underlays %}
        edit "{{underlay.port}}" {# for VLANs this is the parent interface ; for non-vlans this is the physical interface #}
            {{ "set speed "~underlay.speed if underlay.speed }}
        next
        edit "{{underlay.name}}"
            set vdom "root"
            {% if underlay.dhcp %}
                set mode dhcp
                set defaultgw disable
                set dns-server-override disable
            {% else %}
                set mode static
                set ip {{underlay.ipmask}}
            {% endif %}
            {% if underlay.vlanid %}
                set type vlan
                set interface "{{underlay.port}}"
                set vlanid {{underlay.vlanid}}
            {% else %}
                set alias "{{underlay.alias}}"
            {% endif %}
            set allowaccess ping
            set role wan
            set estimated-upstream-bandwidth 100000
            set estimated-downstream-bandwidth 100000
            set monitor-bandwidth enable
            set vrf {{vrf_wan}}
        next
    {% endfor %}

    edit "{{lan.port}}"
        set vdom "root"
        set mode static
        set ip {{lan.ipmask}}
        set allowaccess ping
        {% if ipv6 %}
            config ipv6
                set ip6-address {{lan.ipmask|ipv4_to_ipv6}}
                set ip6-allowaccess ping
            end
        {% endif %}
        set alias "{{lan.alias}}"
        {{ "set speed "~lan.speed if lan.speed }}
        set monitor-bandwidth enable
        set vrf {{vrf_wan}}
    next
    edit "lo-BGP"
        set vdom "root"
        set ip {{loopback}} 255.255.255.255
        set allowaccess ping
        {% if ipv6 %}
            config ipv6
                set ip6-address {{loopback|ipv4_to_ipv6}}/128
                set ip6-allowaccess ping
            end
        {% endif %}
        set type loopback
        set role wan
        set vrf {{vrf_wan}}
    next
end

# DHCP Server for LAN

config system dhcp server
    edit 10
        set interface {{lan.port}}
        set default-gateway {{ lan.ip }}
        set netmask {{ lan.mask }}
        set lease-time 3600
        set dns-service default
        set ntp-service default
        config ip-range
            edit 1
                set start-ip {{ lan.network | ipmath(101) }} {# A single IP is allocated #}
                set end-ip {{ lan.network | ipmath(101) }}
            next
        end
    next
end