###############################################################################################################
# FW Policies
# no IPS profile is applied because IPS process did not start correctly when mixing AppCtrl + IPS profiles

config application list
    edit "appctrl_poc"
        set comment "Monitor all applications."
        config entries
            edit 255
                set application 7930 7931 7932
                set action pass
            next
            edit 1
                set action pass
            next
        end
    next
end

# Policies

config system zone
    edit "LAN"
        set interface {{lan.port}}
    next
end

config firewall policy
    edit 1
        set name "Deny Internet"
        set srcintf "LAN"
        set dstintf "INTERNET"
        set srcaddr "RFC1918-GRP"
        set dstaddr "RFC1918-GRP"
        set schedule "always"
        set service "ALL"
        set logtraffic all
        set comments "Prevent private traffic to leak over the Internet"
        set global-label "INTERNET"
    next
    edit 2
        set name "Internet (DIA)"
#         set name "Internet"
        set srcintf "LAN"
        set dstintf "INTERNET"
        set srcaddr "Corporate"
        set dstaddr "Internet"
        set action accept
        set schedule "always"
        set service "ALL"
        set utm-status enable
        set ssl-ssh-profile "deep-inspection"
        set av-profile "default"
        set application-list "appctrl_poc"
        set logtraffic all
        set nat enable
        set comments "Direct Internet Access"
        {% if not npu %}
            set passive-wan-health-measurement enable
            set app-monitor enable
            set auto-asic-offload disable
        {% endif %}
        set global-label "INTERNET"
    next
    edit 3
        set name "Internet (SIA)"
        set srcintf "LAN"
        set dstintf "SIA"
        set srcaddr "Corporate"
        set dstaddr "Internet"
        set action accept
        set schedule "always"
        set service "ALL"
        set utm-status enable
        set ssl-ssh-profile "deep-inspection"
        set application-list "appctrl_poc"
        set logtraffic all
        set comments "SSE Internet Access"
        {% if not npu %}
            set passive-wan-health-measurement enable
            set app-monitor enable
            set auto-asic-offload disable
        {% endif %}
        set global-label "INTERNET"
    next
    edit 10
        set name "Corporate Out"
        set srcintf "LAN"
        set dstintf "VPN"
        set srcaddr "Corporate"
        set dstaddr "Corporate"
        set action accept
        set utm-status enable
        set ssl-ssh-profile "deep-inspection"
        set application-list "appctrl_poc"
        set schedule "always"
        set service "ALL"
        set logtraffic all
        set comments "Corporate Services"
        {% if not npu %}
            set passive-wan-health-measurement enable
            set app-monitor enable
            set auto-asic-offload disable
        {% endif %}
        set global-label "VPN"
    next
    edit 11
        set name "Corporate In"
        set srcintf "VPN"
        set dstintf "LAN" "lo-BGP"
        set srcaddr "Corporate"
        set dstaddr "Corporate"
        set action accept
        set schedule "always"
        set service "ALL"
        set logtraffic all
        set comments "no UTM inbound - it is applied outbound"
        {% if not npu %}
            set passive-wan-health-measurement enable
            set app-monitor enable
            set auto-asic-offload disable
        {% endif %}
        set global-label "VPN"
    next
end
