###############################################################################################################
# Static routing

{% if vrf_wan == 0 %}
# OOB is in VRF 0 so no need for default static routes 999 via Fabric Studio gateway if the WAN VRF is also in VRF 0
# since there will already exist default routes via the Internet WAN interfaces
    config router static
        delete 999
    end
{% endif %}

# MPLS underlay (distance 21 to make it float after possible eBGP similar route)

config router static
    edit 1
        unset gateway
        unset device
#        set dst {{wan.mpls_summary.network}}
        set dstaddr "MPLS_summary"
        set device "{{wan.mpls1.name}}"
        {{ "set dynamic-gateway enable" if wan.mpls1.dhcp else "set gateway %s.254"%(wan.mpls1.subnet) }}
        set comment "MPLS underlay"
        set distance 21
    next
end

# Static default-routes

# With BGP-on-loopback design, it is recommended to configure **default route** on the Spokes towards all the overlays
# default-route is always configured over all overlays
config router static
    edit 2
        set sdwan-zone "INTERNET" "SIA" "VPN"
        set comment "VRF {{vrf_wan}} default-route via Internet (DIA+SIA) and Overlays"
    next
    edit 3
        set dstaddr "BGP-HUBS"
        set distance 254
        set blackhole enable
        set vrf {{vrf_pe}}
        set comment "Prevent trying to establish BGP Peering with HUB1 via HUB2 (or HUB2 via HUB1)"
    next
end

