### SD-WAN neighbors -----------------------------------------------

{# Must be defined after BGP config #}

{% if region == 'West' %}
# Dual-Hub failover strategy = traffic moves from H1 to H2 only after all H1 links are out-sla
# The SD-WAN rules to the Hubs must be consistent with this strategy
config system sdwan
    config neighbor
        edit "10.200.{{region_id}}.251"
            set health-check "SLA_VPN"
            set member 111 122 133
            set route-metric priority
        next
        edit "10.200.{{region_id}}.252"
            set health-check "SLA_VPN"
            set member 211 222 233
            set route-metric priority
        next
    end
end
{% endif %}
